### PR TITLE
Remove duplicate programming for forwarding tables

### PR DESCRIPTION
**Pull request by nupuruttarwar**
In LNW_v2, FDB entries are programmed by OVS sidecar when the MAC learning happens. It's not required to program l2_fwd_tx_table and l2_fwd_rx_table through krnlmon for new neighbor netlink message for every RIF interface to avoid duplication

### CODE REVIEW

**Comment by 5abeel** [comment]
Please use a descriptive title for PR (and avoid company-internal numbers indicating bug number)

**Comment by nupuruttarwar** [comment]
> Please use a descriptive title for PR (and avoid company-internal numbers indicating bug number)

Done

**Review by ffoulkes — APPROVED** [review]
LGTM

**Review by 5abeel — APPROVED** [review]
LGTM

**Comment by ffoulkes** [comment]
Nit: Krnlmon has its own repository, so it isn't necessary to say "for krnlmon" in the title.

**Pull request merged**
