### PR TITLE
Backport ES2K changes to ipdk-io

### PR DESCRIPTION
**Pull request by ffoulkes**

### CODE REVIEW

**Review by nupuruttarwar — APPROVED** [review]
Apart from 'MEV' references in comments, LGTM

**Review by n-sandeep — APPROVED** [review]
Lokks good to me

**Review by 5abeel — APPROVED** [review]
LGTM

**Comment by ffoulkes** [comment]
> Apart from 'MEV' references in comments, LGTM

Dan has instructed us to merge the ES2K changes first. It is okay for us fix this in public view (which makes me much happier. Our top priority is to move off intel-innersource and reestablish transparency in what we're doing.

**Pull request merged**
