### PR TITLE
Fix compile error when LNW_VERSION=2

### PR DESCRIPTION
**Pull request by ffoulkes**

### CODE REVIEW

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Comment by 5abeel** [comment]
Do the included files change based on the version? I dont see any `#ifdef` wrapped around for different versions - can you clarify

**Comment by 5abeel** [comment]
I see that the changes only go into the lnw-v2 directory of relevant files.

**Review by 5abeel — APPROVED** [review]
LGTM

**Comment by ffoulkes** [comment]
> Do the included files change based on the version?

`LNW_VERSION` causes both a cmake conditional and a C conditional to be defined (`LNW_V2` or `LNW_V3`).

It is applied by means of:

1. `#ifdefs` in the C/C++ source files,
2. Selecting the version-specific subdirectory in `switchapi/es2k/CMakeLists.txt`.

**Pull request merged**
